### ISSUE TITLE
[Base] 기반 코드 분석🤔

### ISSUE THREAD

**Issue by yymin1022** [CAU-OSS-2023-Team15/Project-1#1]
## Summary
- Project 기반 코드 분석

## Description
- [원본 Repository](https://github.com/Michael-Vanderford/electron-file-manager) 에서 Clone 해온 프로젝트 기반 코드를 분석합니다.
- 각자 코드 분석 완료 시, 하단에 Comment를 작성해주세요

**Comment by yymin1022** [comment]
프로젝트 기반 코드 분석 완료하였습니다!
모듈화가 거의 되어있지 않아서 작업 중에 Conflict를 주의해야겠네요..

**Comment by falconlee236** [comment]
프로젝트 기반 코드 분석 완료했습니다!!
일렉트론의 ipc모듈 통신과 프로세스 구조를 중점적으로 공부했습니다. (main vs renderer)

**Comment by jiyuneel** [comment]
프로젝트 기반 코드 분석 완료!!!
코드가 좀 많이 길어서 쉽지 않네요....

**Comment by sehwanii** [comment]
프로젝트 기반 코드 분석 완료했습니다.
일렉트론 통신 구조를 중점으로, 관계 파악을 중점으로 보았습니다.
