### ISSUE TITLE
[DEV] VCS - Git Merge

### ISSUE THREAD

**Issue by yymin1022** [CAU-OSS-2023-Team15/Project-1#37]
## Summary
- VCS 기능을 구현합니다.

## Description
- Git Branch Merge 기능을 구현합니다.
- `git merge TARGE_BRANCH` 명령의 실행 결과와 동일합니다.

**Comment by falconlee236** [comment]
에러나 성공시 계속 dialog를 띄우는 것보다 프로그램 좌 하단부에 메시지를 띄우는것이 낫다고 회의 결과 판단이 되어 다시 issue를 다시 열었습니다.
